### PR TITLE
Bounding box hunt

### PR DESCRIPTION
**Pull request by nschein**
These are the results of my latest experiments. Some code cleaning, some debugging code. Most important, there is a background class now.

### CODE REVIEW

**Review by tyagi-iiitv — APPROVED** [review]

**Comment by tyagi-iiitv** [comment]
This is some serious heavy lifting, thanks :)

**Comment by scrouzet** [comment]
In the prediction script, the data used are DATA_ROOT = "../validation_small". Is there any description of how this one is built? I did not find it.

Thanks for the great work!

**Comment by nschein** [comment]
> In the prediction script, the data used are DATA_ROOT = "../validation_small". Is there any description of how this one is built? I did not find it.
> 
> Thanks for the great work!

Hi. For my tests I just copied one batch of examples from the kitti test data with the same structure as for the rest of the training. No scripts involved.

**Comment by scrouzet** [comment]
Do you mean copied from the training data and not test data? Because AFAIK (but I may be wrong) there is no label in the official KITTI test data, and those are used here in the prediction code.

**Comment by nschein** [comment]
Yeah, sorry about that, I meant the training data. As I am currently still testing this repo, I need some labels to verify the results, i.e., the actual test split is of no use to me at the moment.

**Pull request merged**
