### PR TITLE
Better predictions

### PR DESCRIPTION
**Pull request by nschein**
This finds accurate bounding boxes on a small data set.
I added an opencv requirement because the have NMS for rotated bounding boxes.
Also, the background class is removed again, because class and bbox prediction work now.
Note, I changed the loss weights away from the original paper, because that lead to far better results for my tests.

### CODE REVIEW

**Comment by tyagi-iiitv** [comment]
Thanks Nico!

**Comment by tyagi-iiitv** [comment]
Hi Nico, just wanted to know if you tested the network on the Kitti dataset? Or was it some other dataset?

**Comment by nschein** [comment]
Hey, I used the Kitti data set. I trained for 24k iterations on 5 samples for initial tests. Admittedly, this is a small sample size, but in previous versions this was already making troubles. I did not do larger tests so far. Counting on the community ;-)

**Comment by tyagi-iiitv** [comment]
sounds good, I'm actually training it on the complete Kitti dataset this time, let's see how the results turn out to be. BTW, do you remember the approx. loss value (total and occupancy) for the test you ran (0.7 occ threshold) by any chance?

**Comment by nschein** [comment]
Sure. I expect, however, that you won't reach quite these values -- in meaningful time - when training on all the data at the same time.
angle loss: 3e-4, clf loss: 2e-5, heading loss: 8e-6, localization loss: 1e-6, occupancy loss: 1.4e-3, size loss: 2e-6
total loss: 1.4e-3

**Pull request merged**
